from . import BaseController
import numpy as np

### CURRENT RESULTS: ###
# Average lataccel_cost:  5.091, average jerk_cost:  74.67, average total_cost:  329.2
# Using: [0.7121565271743499, 0.2932924501687073, -0.1988950353056675, -0.05609751334901771, 
#         0.3216861364031248, 0.6786277013487406, 0.3329273203505607, -0.24491526925201154]
# Generated by evo_opt.py
#
# Average lataccel_cost:  3.935, average jerk_cost:  40.56, average total_cost:  237.3
# Using: [0.5409599547115298, 0.07970954970956051, -0.2824890055969795, -0.01592360749769923, 
#         0.18245195061327055, -0.0316273863700143, 0.5554760572956762, -0.47158426200729625]
# Generated by my_evo_opt.py


class Controller(BaseController):
  """
  A more advanced PID controller
  """
  def __init__(self, 
      params=[0.5409599547115298, 0.07970954970956051, -0.2824890055969795, -0.01592360749769923, 
              0.18245195061327055, -0.0316273863700143, 0.5554760572956762, -0.47158426200729625]
      ):
    self.p = params[0]
    self.i = params[1]
    self.d = params[2]
    self.dd = params[3]
    self.alpha = params[4]
    self.beta = params[5]
    self.gamma1 = params[6]
    self.gamma2 = params[7]

    self.error_integral = 0
    self.prev_error = 0
    self.prev_prev_error = 0

  def gain_schedule_p(self, v):
    return self.p * (1.0 / (1 + self.alpha * v))

  def gain_schedule_i(self, v):
    return self.i * (1.0 / (1 + self.beta * v))

  def gain_schedule_d(self, v, roll):
    return self.d * (1.0 / (1 + self.gamma1 * v)) * np.exp(-self.gamma2*abs(roll))


  def update(self, target_lataccel, current_lataccel, state, future_plan):
    v = state.v_ego*.1
    roll = state.roll_lataccel*.1
    p = self.gain_schedule_p(v)
    i = self.gain_schedule_i(v)
    d = self.gain_schedule_d(v, roll)
    dd = self.dd

    error = (target_lataccel - current_lataccel)
    error_diff = error - self.prev_error
    error_ddiff = self.prev_error - self.prev_prev_error

    # Clegg integrator:
    if np.sign(error_diff) != np.sign(error_ddiff):
        self.error_integral -= error
    else:
        self.error_integral += error

    self.prev_prev_error = self.prev_error
    self.prev_error = error

    return p * error + i * self.error_integral + d * error_diff + dd * error_ddiff
